version: '3'
services:
  portfolio-v3:
    container_name: portfolio-v3
    environment:
      PORT: 3000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    restart: always

volumes:
  postgres_data:
  
